version: "3.8"

volumes:
  # Service's data storage volume
  shrtd-data:


services:
  shrtd:
    image: unwire/shrtd:latest
    environment:
      SHRTD_ADDRESS: "0.0.0.0"
      SHRTD_PORT: "8000" # Beware, edit the ports section of the service too
      SHRTD_REDIS_URL: "redis://redis:6379"
      SHRTD_DATA_DIR: "/data" # Beware, edit the volumes section of the service too
      SHRTD_SLUG_LENGTH: 13
      SHRTD_MAX_FILE_SIZE: 128
      SHRTD_MAX_PASTE_SIZE: 1
    volumes:
      - "shrtd-data:/data"
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      redis:
        condition: service_healthy
  redis:
      image: redis:6.2.3
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 1s
        timeout: 3s
        retries: 30
