name: CI

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  build-x86_64:
    name: Build for Linux x86_64 @ musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - run: ls -lah target/release

  # build-aarch64:
  #   name: Build for Linux aarch64 @ musl
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
